<#import "/template.ftlh" as layout />
<@layout.template title="Page Not Found">
<img id="construction-image" class="mx-auto d-block" src="/images/website_under_construction.png" alt="Person undergoing anesthesia" />
<p class="text-center">Sorry, it looks like that page doesn't exist, or is still under construction.<br/>Check back later to see if it's up!</p>
<link rel="stylesheet" href="/css/error.css" />
</@layout.template>