<#import "/subpage/career_pathways/careerPathwaysSubpage.ftlh" as layout />
<@layout.careerPathwaysSubpage title="CRNA">
<img id="crna-image" class="mx-auto d-block career-pathways-image" src="/images/subpage/career_pathways/crna.png" alt="CRNA at work" />
<h4 id="Role">Role</h4>
<p>Certified Registered Nurse Anesthetists (CRNAs) are advanced practice registered nurses who plan and deliver anesthesia, pain management, and related care to patients of all health complexities across the lifespan. All programs for CRNAs have moved from a master's degree to a Doctor of Nurse Anesthesia Practice (DNAP)</p>

<h4 id="JobDuties">Job Duties</h4>
<ul>
    <li>Elicit a pre-anesthesia health history and perform a physical examination</li>
    <li>Establish patient monitoring devices and intravenous access</li>
    <li>Apply and interpret advanced monitoring techniques</li>
    <li>Participate in all aspects of a patient's anesthetic including, but not limited to, induction, maintenance, and emergence</li>
    <li>Secure the patient's airway through a mask, endotracheal tube, or laryngeal mask airway</li>
    <li>Interpret and record the patient's physiological and pharmacological status</li>
    <li>Provide continuity of care into and during the post-operative period</li>
    <li>Inserting/maintaining arterial catheters</li>
    <li>Inserting/maintaining venous catheters</li>
    <li>Inserting/maintaining lumbar epidural catheters</li>
    <li>Administer spinal anesthesia</li>
    <li>Administer regional anesthesia blocks</li>
    <li>Administer general anesthesia</li>
</ul>

<h4 id="Requirements-Timeline">Requirements/ Timeline</h4>
<p>To get into a BSN program, the final two years of undergrad for nursing students, you need to complete undergraduate courses such as chemistry, anatomy, and physiology. You also need to take the Test of Essential Academic Skills (TEAS) Exam. A 70% is considered a good score while <a href="https://www.test-guide.com/teas-test-scores.html" target="_blank">over an 80% is exemplary</a></p>
<p>Once in nursing school, you will need a 75% or higher to pass your classes followed by passing the National College Licensure Exam (NCLEX).</p>
<p>CRNA or DNAP schools require extra course(s) after your BSN such as organic chemistry or biochemistry or <a href="https://www.missouristate.edu/Anesthesia/DNAP/Program-Requirements.htm" target="_blank">Preparation for Anesthesia School</a></p>
<p>Additionally, you will need <a href="https://www.coacrna.org/accreditation/accreditation-standards-policies-and-procedures-and-guidelines/" target="_blank">1-3 years of critical care experience</a> depending on the school you're applying to.</p>
<p>DNAP schools require you to be certified in Critical Care Nursing (<a href="https://www.aacn.org/certification/get-certified/ccrn-adult" target="_blank">CCRN</a>), which is an exam you can take after 1 year of critical care experience.</p>
<p>Or get a GRE score with <a href="https://catalog.missouristate.edu/preview_program.php?catoid=7&poid=2087" target="_blank">153 Verbal reasoning (60th percentile), 150 Qualitative Reasoning (38th percentile), and 3.5 Analytical Writing (42nd percentile)</a></p>
<p>DNAP school is 3 years with through the National Board of Certification and Recertification for Nurse Anesthetists (<a href="https://www.nbcrna.com/" target="_blank">NBCRNA</a>).</p>

<h4 id="Costs-Salary">Costs/ Salary</h4>
<p class="mb-1">-<a href="https://www.missouristate.edu/Nursing/Undergraduate/costs.htm" target="_blank">$45,000 undergraduate school</a></p>
<p class="mb-1">-$140,000 DNAP = <a href="https://www.missouristate.edu/Anesthesia/dnap/Costs.htm" target="_blank">$83,000 Tuition</a> + <a href="https://finaid.umkc.edu/affordability/medicine-cost-estimate.html" target="_blank">$57,000 Room and board for 3 years</a></p>
<hr class="w-50 mt-0 mb-1" />
<p>$185,000 Total Cost</p>
<p>One of the benefits of being a CRNA is the critical care work between your BSN and DNAP school can help cover some of the costs of your school since ICU nurses make an average of $70,000 a year <a href="https://www.nursingprocess.org/icu-nurse-salary.html" target="_blank">ICU Nurse Salary By State – (2025 Figures)</a>.</p>
<p>Pay is great for CRNAs with a starting salary at $200,000 and capping at $300,000 in an Anesthesia Care Team (ACT) Model and $400,000 in the states you can practice independently. <a href="https://nursejournal.org/nurse-anesthetist/crna-supervision-requirements/" target="_blank">CRNA Supervision Requirements By State | NurseJournal.org</a></p>

<h4 id="JobOutlook">Job Outlook</h4>
<p>CRNAs have a great job outlook with over 5,000 positions (10% Growth) <a href="https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm#tab-6" target="_blank">Nurse Anesthetists, Nurse Midwives, and Nurse Practitioners: Occupational Outlook Handbook: U.S. Bureau of Labor Statistics</a> to be added by 2033. CRNAs can practice in a wide range of locations such as Trauma Centers, rural hospitals, eye clinics, and ketamine clinics. CRNAs can practice independently in 32 states or be supervised in an ACT model.</p>
</@layout.careerPathwaysSubpage>